"""add_password_reset_tokens_table

Revision ID: 8cc23c178ece
Revises: d39fa7cf25af
Create Date: 2026-05-25 20:49:42.453375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cc23c178ece'
down_revision: Union[str, None] = 'd39fa7cf25af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
