"""add_password_reset_tokens_table

Revision ID: 8cc23c178ece
Revises: d39fa7cf25af
Create Date: 2026-05-25 20:49:42.453375

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '8cc23c178ece'
down_revision: str | None = 'd39fa7cf25af'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
